# Generated by Django 4.2.5 on 2023-10-07 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OkodukaiModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.CharField(max_length=100)),
                ('price', models.IntegerField()),
                ('notes', models.TextField()),
            ],
        ),
        migrations.AlterField(
            model_name='memo',
            name='title',
            field=models.CharField(max_length=100),
        ),
    ]
