# Generated by Django 4.2.5 on 2023-10-07 13:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_okodukaimodel_alter_memo_title'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='OkodukaiModel',
            new_name='KodukaiModel',
        ),
    ]
