# Generated by Django 4.2.5 on 2023-10-08 09:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0003_rename_okodukaimodel_kodukaimodel'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='KodukaiModel',
            new_name='PkMnyNote',
        ),
    ]
